language: java
jdk: oraclejdk8
notifications:
  email: false
env:
  global:
  - TERM=dumb

before_install: '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || openssl aes-256-cbc -K $encrypted_28a2bffe3d7c_key -iv $encrypted_28a2bffe3d7c_iv -in keystore.jks.enc -out keystore.jks -d'
install: ./gradlew build -S

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock

branches:
  except:
  - /^release-.*$/

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew curseforge -S
    on:
      all_branches: true
      repo: CyclopsMC/EverlastingAbilities
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: JtEsae1rYO4+q6TcpeQhdfeLafFpQkaO5sc9ZoEbbaO/O0Yiy5OeoPuoxLpZs7xkokLUdWH41I3j1mYniV4EIS5lmi+hiZBAGCQ+F70g4HpGz2rBuN1iv02j64fMtmUTqQUULRKiS+I9NXhho2YwOONgNdXLluxFEDQJZ6NxYCg1sN5Rcz05Rr6sMkpZeeSjDg+uXyfavitFTKqc1tJJc4spIWIDqKEXOinBOhkuQqLyhTpTE7Rl0bSc0OZ1jKn7js7lldBjhJq9CorICg/6IMCNDv2oKGucnZxhdjK/yLPZxvPgkV4SIUZ/zPSsSwoX+5ACkP+PnM4oWQobVhQN9LGqgppOjEpkQXxG5F/Y9fqtJoB2Z4kG8+RikvVJeOjpvlRnGNrj5tTD3RKK/1gwkKp3ysfMxmBmGFBMMU+ldRHDyhgxIiJb7sW+PBPPU0ru5OIsPlE84mwbpPrB71eloCQv+SFC51E0XNlXgMls/yIRkRBfcx8F5wLxRkHkYoIkIDaFCPYX++jLZ/ErKVYiKCdXNK34tt1usx9VGr1FX7rxRDI6hg2ILS/jjgzjL8rpUCuzNDsdv0VjLgDTJ+D6pV9FMUyY1fMuUM5/F6uZBt5HbqW9Gjf8LQi8baFy9Yk5N7D1xWkHDQAbYViz2OrRNxI7v3YKPbaNbFa+9sE9hs4=
    on:
      all_branches: true
      repo: CyclopsMC/EverlastingAbilities
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./gradlew uploadArchives -S
    on:
      all_branches: true
      repo: CyclopsMC/EverlastingAbilities
      condition: "$TRAVIS_BRANCH =~ ^(master|release).*$"
