modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/CyclopsMC/EverlastingAbilities/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/everlastingabilities"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="everlastingabilities"
version="${file.jarVersion}"
displayName="EverlastingAbilities"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/everlastingabilities.json"
description='''
Discover, share and conquer abilities that stick.
'''
[[dependencies.everlastingabilities]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.11.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.everlastingabilities]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.everlastingabilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,]"
    ordering="NONE"
    side="BOTH"
