modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/EverlastingAbilities/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/everlastingabilities"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="everlastingabilities"
version="${file.jarVersion}"
displayName="EverlastingAbilities"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/everlastingabilities.json"
description='''
Discover, share and conquer abilities that stick.
'''
[[dependencies.everlastingabilities]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.20.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.everlastingabilities]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.everlastingabilities]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,]"
    ordering="NONE"
    side="BOTH"
